### PR TITLE
You don't need to sneak to place blocks

### PR DESCRIPTION
**Pull request by starforcraft**
if you aim on a Centrifuge Block

P.S. I made the [Centrifuge Tiers](https://www.curseforge.com/minecraft/mc-mods/centrifuge-tiers) mod :)

### CODE REVIEW

**Comment by Epic428** [comment]
I’ll check both of these PRs out and merge where I can. I also have to see why the build checks failed. Github actions has been weird about compiling the mod

**Comment by starforcraft** [comment]
okay :)

**Comment by Epic428** [comment]
Btw https://discord.gg/xcrMeJVC - if you'd like to join our discord - I'll give role to join dev chat

**Comment by starforcraft** [comment]
I am in :) my Name in Discord is Ultramega#3662

**Pull request merged**
