### PR TITLE
Fix 1.16.5 bee pollinate same target

### PR DESCRIPTION
**Pull request by Naliwe**
I figured I'd just create the PR directly instead of opening an issue :)

I think it would fix this problem

Which is very annoying x) It hinder production a lot

Tell me if I missed anything

### CODE REVIEW

**Comment by Naliwe** [comment]
I mean long term solution should probably be load balancing the bees on the available resources but eh~ That should suffice

**Comment by ThatGravyBoat** [comment]
The first thing the picture you've linked is not what you've made a PR for.
The second thing is the entity pollination flower goes from the bee outwards exactly as the vanilla bee does with their finding of flower and as our block flower does.
The third thing is we fix that a few updates ago so whatever pack that image is from is using an outdated version of the mod

**Comment by Naliwe** [comment]
Alright, thanks, it seemed too simple to be true x)

I updated my dependencies, it seems to be fine now! Thanks

**Comment by Epic428** [comment]
Closing and marking as resolved. Thanks for trying to help!

**Pull request closed without merging**
