### PR TITLE
update zh_cn translations of version 1.0.0-alpha on May 21

### PR DESCRIPTION
**Pull request by zheung**
Keep going on :)

### CODE REVIEW

**Comment by Epic428** [comment]
I just saw this PR lol. Doing a major rewrite of the mod currently :p that’s why you prolly see a lot of stuff changing.

**Comment by Epic428** [comment]
Oh also with the rewrite I will be needing to update patchouli book as well. So there will be plenty more stuff needing translations lol

**Comment by zheung** [comment]
> Oh also with the rewrite I will be needing to update patchouli book as well. So there will be plenty more stuff needing translations lol

You can remind me to translate when you think it is appropriate :)

**Comment by Epic428** [comment]
Ah no worries. If you have discord you can join our discord https://discord.resourcefulbees.com and I can give you access to our dev chat and then you can follow our progress more as well.

**Pull request merged**
